### PR TITLE
checkout auraed repo to fix build

### PR DESCRIPTION
**Pull request by taniwha3**
Signed-off-by: Tani <111664369+taniwha3@users.noreply.github.com>

### CODE REVIEW

**Comment by krisnova** [comment]
@cla-bot check

**Comment by krisnova** [comment]
@cla-bot check

**Comment by krisnova** [comment]
@MalteJ unsure why its not letting my CLA go through?

**Comment by MalteJ** [comment]
@krisnova taniwha3 was not in the old Google Forms table. Therefore also not in the new database.

**Pull request merged**
